### ISSUE TITLE
Add some small code snippets in the README

### ISSUE THREAD

**Issue by sidkshatriya** [becls/swish#1]
Thanks for putting this up.

It may be a good idea to add an excerpt from your documentation (which is current a PDF I understand) into the README. Basically, some code snippets and basics so that users can get an idea of swish and explore deeper if they are interested.

Right now they will have to build the PDF to know more about swish...which is a leap a casual visitor may not be willing to make right away.

**Comment by burgerrg** [comment]
We now have a link to the PDF from the README.
