### ISSUE TITLE
swish doc web hosting

### ISSUE THREAD

**Issue by yanshuf0** [becls/swish#10]
I'd be happy to build a website to host some of the swish docs that have to be made with pdflatex on a web app deployed to github pages if you would be interested. In general I think TeX is kind of a pain as it's implementations are not always installed and are often multi gigabyte. The casually interested may not be willing to invest that much to read the docs (the pdf is quite good actually!). Let me know your thoughts on this.

**Comment by burgerrg** [comment]
Thank you for your kind offer! I configured a gh-pages branch on the repository and placed swish.pdf on it along with a link from README.md.
