### ISSUE TITLE
Question: How to use my wiredtiger database library

### ISSUE THREAD

**Issue by amirouche** [becls/swish#11]
Hello,

I am (re) starting a project that I have done previously using Guile where I planned to use guile-fibers. Maybe swish can do the job.

I have a database library built on top of wireditger which is a database library that is hosted in the process that uses it.

So, my question is, can make use of the database library without having to use another process and serialize queries over the wire.

Thanks in advance!

**Comment by burgerrg** [comment]
So you're planning to integrate the wiredtiger library into the Scheme process? If so, you'll need to write some glue code, especially if wiredtiger does not support an asynchronous interface. The glue code would manage the threads needed by wiredtiger and marshal the queries and results from and to the Scheme main thread. See src/swish/sqlite.c for an example of using the SQLite library from Scheme.

**Comment by burgerrg** [comment]
The Scheme code runs single threaded. Consequently, if a blocking operation is required, it must be done on another thread, and the result sent back to the Scheme main thread.

**Comment by amirouche** [comment]
Maybe I will re-open the issue later, if I decide to go with swish. Tx!
