### ISSUE TITLE
Question: how does swish compare to guile-fibers

### ISSUE THREAD

**Issue by amirouche** [becls/swish#12]
https://github.com/wingo/fibers

**Comment by burgerrg** [comment]
I'm not familiar with the fibers project, but a quick look indicates it uses epoll on Linux, which is what libuv uses on Linux in Swish. It seems to use the same idea of continuations and asynchronous I/O. Swish is cross-platform and implements Erlang-style message-passing concurrency.

**Comment by amirouche** [comment]
Thanks for the feedback. I think guile-fibers also does something similar to erlang.

I am not sure. Tx!
