### ISSUE TITLE
Why does not Swish procedure naming comply with Scheme?

### ISSUE THREAD

**Issue by prettykingking** [becls/swish#151]
In Swish, many procedure's name separated by a colon `:`.

Interfaces like `(queue:add x q)`, `(db:filename who)`, `(http:add-file-server arg ...)`.

I think a dash `-` should be used instead on which described in [Scheme naming convention](https://scheme.com/tspl4/intro.html#./intro:h2). Maybe a colon `:` is best practice in community?

**Comment by payneca** [comment]
You are seeing an artifact of blending Erlang language concepts with Scheme. Erlang uses a "Module:Function(Args)" style, like `gen_server:start_link(Name, Arg1, Arg2)`. We chose to use the Scheme library name and a colon as a prefix to help indicate "this function is more like Erlang than Scheme". 

The `queue` library probably seems like it should user Scheme's convention, except that it internally uses Erlang's pattern matching. So, we use the Erlang convention.

**Comment by prettykingking** [comment]
OK, I understand. Respect the significant message passing concept exported from Erlang.
