### ISSUE TITLE
Discuss: may we skip make documents when building?

### ISSUE THREAD

**Issue by qzivli** [becls/swish#16]
Some dependencies have a high probability of installation failure, e.g., tex's and dot's. I think it is not a good idea to let these failure to prevent the novice from trying to use swish. Should we provide a option to let user skip the step of make documents?

**Comment by burgerrg** [comment]
You can use `make swish` to build everything except the docs.

**Comment by burgerrg** [comment]
Changeset b0de814676a9bf2a471c5dbaf5223cdfa650ae67 makes this the default behavior.
