### ISSUE TITLE
Weird effect when exiting fullscreen video

### ISSUE THREAD

**Issue by andreclerigo** [becls/swish#169]
**Describe the bug**
When exiting full-screen videos, it seems that the resizing is affected by a previous window size set by swish shortcuts

https://github.com/user-attachments/assets/771d8d92-c30d-4a60-8858-c4815f165123

**How to reproduce the bug**

1. Resize a window using swish shortcuts (not maximized)
2. Maximize your window
3. Enter full-screen mode on a video
4. Exit full-screen mode

**Expected behavior**
When exiting fullscreen the video should try to resize to the windows's current size

**Software environment**
Include the output of `swish-build --info`

```
Not found, Swish app version in 1.11
```

**Comment by owaddell** [comment]
You may be looking for another project (perhaps [this one?](https://setapp.com/apps/swish)). The repository and issues here are for a general-purpose programming language with concurrency and pattern-matching features.

**Comment by andreclerigo** [comment]
Well this is embarrassing, I'm sorry 😅
