### ISSUE TITLE
What is an engine? How should swish be run?

### ISSUE THREAD

**Issue by yanshuf0** [becls/swish#18]
Swish is described as a concurrency engine. Does engine imply it's related to engines in chez? Is swish meant to be run in place of chez when running or compiling scheme programs? Running swish on my terminal seems to bring up a scheme repl. Is swish just chez scheme with added functionality?

**Comment by burgerrg** [comment]
Swish is an extension of Chez Scheme for concurrency-oriented programming. Its engine is loosely related to engines in Chez Scheme in that it uses software timer interrupts and continuations to provide concurrent processes.

**Comment by yanshuf0** [comment]
Ok thanks! Let me see if I can build something with it. I see the version is 0.0.0, does that mean it's not ready for serious use yet?

**Comment by burgerrg** [comment]
Much of the code comes from the Windows-only version that has been used in production. The new code is the libuv-based operating system interface. The version of 0.0.0 indicates that we've not yet completed our full inspection and testing of the system. We may make some breaking API changes before the first release.

**Comment by yanshuf0** [comment]
Sounds good, is there an timeline estimate for the release process?

**Comment by burgerrg** [comment]
Unfortunately we don't have a timeline yet. I'm going through a job transition.

**Comment by burgerrg** [comment]
We're making good progress towards our first release.

**Comment by laqrix** [comment]
Thanks for your interest! We're about a year overdue on making a release, but it has finally happened. 2.0.0 is out.  We're light on examples and tutorials, but we believe Swish itself is solid.
