### ISSUE TITLE
Misspelling and unnecessary complexity in error message wording.

### ISSUE THREAD

**Issue by c32hedge** [becls/swish#19]
https://github.com/becls/swish/blob/7bac0a7a6acf8778d0a77b794539e415183c1194/src/swish/http.ss#L613

"fullfilling" should be "fulfilling" (one, then two L's, not two and two).

Also, this message wording is unnecessarily complicated. Suggestions:

* The server was unable to complete the request.

Or, in keeping with some of the other more playful messages:
* I'm sorry Dave, I can't do that.
* I find your lack of server disturbing.

**Comment by burgerrg** [comment]
Thank you for finding this typo! It's fixed with your first suggestion in c7ab0c4b48e00367edada17a35aa3610c3b2e9ec.
