### ISSUE TITLE
Does swish has a benchmark?

### ISSUE THREAD

**Issue by guenchi** [becls/swish#41]
For example a http server benchmark between 

Woo (comme lisp)
Node (Javascript)
Go

etc

**Comment by burgerrg** [comment]
No, but I've used [httperf](https://github.com/httperf/httperf) in the past to measure Swish's http performance.

**Comment by guenchi** [comment]
> No, but I've used [httperf](https://github.com/httperf/httperf) in the past to measure Swish's http performance.

And the result?   (with httperf)

**Comment by burgerrg** [comment]
I ran the following on a 15-inch 2018 MacBook Pro with a 2.6 GHz Intel Core i7, 32 GB 2400 MHz DDR4 RAM, and an SSD drive running macOS 10.14.5:
`httperf --server localhost --port 8080 --num-conn 100`

Both Swish and lighttpd took an average of 0.4 ms to connect, 0.1 ms to respond, and 0.0 ms to transfer the default main page of Swish.

I'd recommend running a benchmark that matches your target application's http usage.
